create table public.reservations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint not null,
  title text not null,
  author text,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  reserved_at timestamptz not null default now(),
  unique (user_id, book_id)
);

create index reservations_user_reserved_idx on public.reservations (user_id, reserved_at desc);

alter table public.reservations enable row level security;

create policy "Students can manage their reservations" on public.reservations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);