create table public.reading_lists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 60),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name),
  unique (user_id, id)
);

alter table public.bookmarks
  add column list_id bigint;

insert into public.reading_lists (user_id, name)
select distinct user_id, 'My list'
from public.bookmarks
on conflict (user_id, name) do nothing;

update public.bookmarks as bookmark
set list_id = reading_list.id
from public.reading_lists as reading_list
where reading_list.user_id = bookmark.user_id
  and reading_list.name = 'My list';

alter table public.bookmarks
  alter column list_id set not null;

alter table public.bookmarks
  add constraint bookmarks_user_list_fkey
  foreign key (user_id, list_id)
  references public.reading_lists (user_id, id)
  on delete restrict;

create index bookmarks_user_list_created_idx
  on public.bookmarks (user_id, list_id, created_at desc);

alter table public.reading_lists enable row level security;

create policy "Students can manage their reading lists" on public.reading_lists
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);