create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  course text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.reading_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint not null,
  title text not null,
  author text,
  last_read_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, book_id)
);

create table public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint not null,
  title text not null,
  author text,
  created_at timestamptz not null default now(),
  unique (user_id, book_id)
);

create index reading_history_user_last_read_idx on public.reading_history (user_id, last_read_at desc);
create index bookmarks_user_created_idx on public.bookmarks (user_id, created_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, course)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'course', '')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.reading_history enable row level security;
alter table public.bookmarks enable row level security;

create policy "Students can view their profile" on public.profiles
  for select using (auth.uid() = id);
create policy "Students can update their profile" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "Students can manage their reading history" on public.reading_history
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Students can manage their bookmarks" on public.bookmarks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
