create table public.catalog_search_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null check (char_length(query) between 1 and 200),
  created_at timestamptz not null default now()
);

create index catalog_search_history_user_created_idx
  on public.catalog_search_history (user_id, created_at desc);

create table public.catalog_book_views (
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint not null,
  title text not null,
  author text,
  item_type text,
  genres text[] not null default '{}',
  subjects text[] not null default '{}',
  series text,
  publisher text,
  publication_place text,
  publication_year integer,
  url text,
  viewed_at timestamptz not null default now(),
  primary key (user_id, book_id)
);

create index catalog_book_views_user_viewed_idx
  on public.catalog_book_views (user_id, viewed_at desc);

alter table public.catalog_search_history enable row level security;
alter table public.catalog_book_views enable row level security;

create policy "Students can manage their catalog search history"
  on public.catalog_search_history
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Students can manage their catalog book views"
  on public.catalog_book_views
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
